name: Redis container setup

on:
  push:
    branches:
      - main

jobs:
  redis-setup:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
